### ISSUE TITLE
Garnet installation not working

### ISSUE THREAD

**Issue by tbretschneider** [code4fun1024/setting-app-for-hyperos#2]
tobi@tyche:~/Downloads$ adb install Settings_GARNETEEAGlobal_from_OS1.0.8.0.UNREUXM.apk 
Performing Streamed Install
adb: failed to install Settings_GARNETEEAGlobal_from_OS1.0.8.0.UNREUXM.apk: Failure [INSTALL_FAILED_INVALID_APK: Package com.android.settings are not updateable.]

My device has 1.0.16.0.UNREUXM

**Comment by code4fun1024** [comment]
I guess the ROM version `1.0.16.0` is too new to downgrade.

**Comment by tyeistired** [comment]
my rom is 1.0.11 same error
