### ISSUE TITLE
settings app for redmi note 11

### ISSUE THREAD

**Issue by superjhay29** [code4fun1024/setting-app-for-hyperos#3]
Hello, i tried various settings app. not a single one of them worked

Device is Redmi Note 11 with HyperOS 1.0.7.0.TGCMIXM android 13

**Comment by code4fun1024** [comment]
[Settings_SPESGlobal_from_OS1.0.3.0.TGCMIXM.apk](https://drive.google.com/file/d/18OjtjeGMt6Ijvwsw4OTqmq20PwB3SdRY/view?usp=sharing)

try this apk
